### ISSUE TITLE
rtl8723be unable to build on Linux Kernel 5

### ISSUE THREAD

**Issue by govi20** [lwfinger/rtlwifi_new#449]
I have updated my Ubuntu Desktop to 19.04, 19.04 has kernel updates to 5. However, when I try to build the project I am getting below error.  **Please check attached logs** [kernel5.txt](https://github.com/lwfinger/rtlwifi_new/files/3108804/kernel5.txt)

Thanks :)

`  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723be/table.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723be/trx.o
  LD [M]  /home/govi/script/rtlwifi_new-master/rtl8723be/rtl8723be.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723com/main.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723com/dm_common.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723com/fw_common.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8723com/phy_common.o
  LD [M]  /home/govi/script/rtlwifi_new-master/rtl8723com/rtl8723-common.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8821ae/dm.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8821ae/fw.o
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8821ae/hw.o
/home/govi/script/rtlwifi_new-master/rtl8821ae/hw.c: In function ‘_rtl8821ae_get_wakeup_reason’:
/home/govi/script/rtlwifi_new-master/rtl8821ae/hw.c:1382:3: error: implicit declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’? [-Werror=implicit-function-declaration]
   do_gettimeofday(&ts);
   ^~~~~~~~~~~~~~~
   do_settimeofday64
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:286: /home/govi/script/rtlwifi_new-master/rtl8821ae/hw.o] Error 1
make[2]: *** [scripts/Makefile.build:515: /home/govi/script/rtlwifi_new-master/rtl8821ae] Error 2
make[1]: *** [Makefile:1584: _module_/home/govi/script/rtlwifi_new-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-13-generic'
make: *** [Makefile:58: all] Error 2
govi@jarvis:~/script/rtlwifi_new-master$ sudo make install
make -C /lib/modules/5.0.0-13-generic/build M=/home/govi/script/rtlwifi_new-master modules
make[1]: Entering directory '/usr/src/linux-headers-5.0.0-13-generic'
  CC [M]  /home/govi/script/rtlwifi_new-master/rtl8821ae/hw.o
/home/govi/script/rtlwifi_new-master/rtl8821ae/hw.c: In function ‘_rtl8821ae_get_wakeup_reason’:
/home/govi/script/rtlwifi_new-master/rtl8821ae/hw.c:1382:3: error: implicit declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’? [-Werror=implicit-function-declaration]
   do_gettimeofday(&ts);
   ^~~~~~~~~~~~~~~
   do_settimeofday64
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:286: /home/govi/script/rtlwifi_new-master/rtl8821ae/hw.o] Error 1
make[2]: *** [scripts/Makefile.build:515: /home/govi/script/rtlwifi_new-master/rtl8821ae] Error 2
make[1]: *** [Makefile:1584: _module_/home/govi/script/rtlwifi_new-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-13-generic'
make: *** [Makefile:58: all] Error 2
`

**Comment by lwfinger** [comment]
On my system, the driver builds correctly with kernel 5.0.X and 5.1.X.

The section that mentions do_gettimeofday occurs in the code
```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(3, 16, 0))
typedef __s32 time64_t;

static inline time64_t ktime_get_real_seconds(void)
{
        struct timeval ts;

        do_gettimeofday(&ts);
        return ts.tv_sec;
}
#elif (LINUX_VERSION_CODE < KERNEL_VERSION(3, 18, 0))
static inline time64_t ktime_get_real_seconds(void)
{
        struct timespec64 tv;

        getnstimeofday64(&tv);

        return tv.tv_sec;
}
#endif
```
From this, do_gettimeofday() is only called for kernels < 3.18. As you have 5.0.13, that should never be called. Do the following:
`find /usr/src/linux-headers-5.0.0-13-generic -name version.h -exec cat {} \;
`
Post the output.

**Comment by QaziSajid** [comment]
I did a few changes in the `core.c` to get mine working.
Replaced(all occurrences) `struct timeval ts;` with `struct timespec64 ts;`
Replaced(all occurrences) `do_gettimeofday(&ts);` with `ktime_get_real_ts64(&ts);`
Some other problems were occurring in the driver for RTL8821ae but I have RTL8723be so I did not want to fix it. Simply deleted the rtl8821ae folder and removed all lines containing rtl8821ae from the Makefile.

**Comment by govi20** [comment]
@lwfinger 
 
`govi@jarvis:~$ sudo find /usr/src/linux-headers-5.0.0-13-generic -name version.h -exec cat {} \; 
[sudo] password for govi: 
#define LINUX_VERSION_CODE 327686
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
`

@QaziSajid Sure. I will give it a try,

**Comment by lwfinger** [comment]
@govi20: That is the kernel version for 5.0.6, even though your headers are for 5.0.0-13.. Your distro probably does that.

@QaziSajid: The conditional code should not require such manual manipulations. Do you have the latest pull?

**Comment by govi20** [comment]
@lwfinger I took the latest clone of code. Build worked perfectly fine on the above kernel updates.
