### ISSUE TITLE
driver does no  longer compile with kernel 4.15

### ISSUE THREAD

**Issue by tatue64** [lwfinger/rtlwifi_new#318]
To solve the problem that my realtek RTL8812AE 802.11ac chip does not support the 5GHz band i used  to compile the drivers provided here.

However, with kernel 4.15 (unstable branch) this does no longer work. I get the following error

    make[1]: Verzeichnis „/usr/lib/modules/4.15.0-1-MANJARO/build“ wird betreten
    CC [M] /home/xxx/treiber/rtlwifi_new/base.o
    In file included from ./arch/x86/include/asm/percpu.h:45:0,
    from ./arch/x86/include/asm/current.h:6,
    from ./include/linux/sched.h:12,
    from /home/xxx/treiber/rtlwifi_new/wifi.h:31,
    from /home/xxx/treiber/rtlwifi_new/base.c:26:
    ./include/linux/kernel.h:6:10: schwerwiegender Fehler: stdarg.h: Datei oder Verzeichnis nicht gefunden
    #include <stdarg.h>
    ^~~~~~~~~~

that is, the file <stdarg.h> is not found. 

I do not know if this is specific for the arch-based Manjaro distribution or a general problem with kernel 4.15.

**Comment by adamreichold** [comment]
Similar problems running OpenSUSE Tumbleweed after upgrade to kernel 4.15:
```
> make clean && make KVER=4.15.0-1-default
make -C /lib/modules/4.15.0-1-default/build M=/home/adam/Downloads/rtlwifi_new modules
make[1]: Verzeichnis „/usr/src/linux-4.15.0-1-obj/x86_64/default“ wird betreten
  CC [M]  /home/adam/Downloads/rtlwifi_new/base.o
/home/adam/Downloads/rtlwifi_new/base.c: In function ‘_rtl_init_deferred_work’:
/home/adam/Downloads/rtlwifi_new/base.c:576:2: error: implicit declaration of function ‘setup_timer’; did you mean ‘sk_stop_timer’? [-Werror=implicit-function-declaration]
  setup_timer(&rtlpriv->works.watchdog_timer,
  ^~~~~~~~~~~
  sk_stop_timer
cc1: some warnings being treated as errors
```

Could this be related to the [recent change](https://old.lwn.net/Articles/735887/) in the kernel's timer API?

**Comment by lwfinger** [comment]
Yes, and the master branch has not been updated. Change to the extended branch, and the repo will again build for you. At the moment, I do not have time to fix master.

**Comment by bkuczenski** [comment]
same problem on extended branch, just upgraded to 4.15.15-1-ARCH

```
@ember:rtlwifi_new$ git status
On branch extended
Your branch is up to date with 'origin/extended'.

nothing to commit, working tree clean
b@ember:rtlwifi_new$ make clean
b@ember:rtlwifi_new$ make
make -C /lib/modules/4.15.15-1-ARCH/build M=/data/GitHub/rtlwifi_new modules
make[1]: Entering directory '/usr/lib/modules/4.15.15-1-ARCH/build'
  CC [M]  /data/GitHub/rtlwifi_new/base.o
In file included from ./arch/x86/include/asm/percpu.h:45:0,
                 from ./arch/x86/include/asm/current.h:6,
                 from ./include/linux/sched.h:12,
                 from /data/GitHub/rtlwifi_new/wifi.h:31,
                 from /data/GitHub/rtlwifi_new/base.c:26:
./include/linux/kernel.h:6:10: fatal error: stdarg.h: No such file or directory
 #include <stdarg.h>
          ^~~~~~~~~~
compilation terminated.
```

**Comment by lwfinger** [comment]
The only times I have seen that error, I needed to do a 'make clean'. Does that help?

**Comment by bkuczenski** [comment]
sorry, it does not- asking at arch forum..

**Comment by bkuczenski** [comment]
running make verbosely, the GCC `-isystem` argument is being set to `/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include' but gcc is now version 7.3.1. I'm not sure where that variable is getting set but it seems unlikely to be a misconfigured gcc implementation in arch.

**Comment by bkuczenski** [comment]
Here is my verbose compiler output: https://pastebin.com/XvQfsWse

**Comment by bkuczenski** [comment]
Anyway, not knowing exactly why the configuration is wrong, creating a symlink to the 7.3.1 folder named 7.3.0 allows the compilation to complete.

**Comment by loqs** [comment]
https://github.com/torvalds/linux/commit/3298b690b21cdbe6b2ae8076d9147027f396f2b1
After the above .cache.mk should be cleaned as well

**Comment by bkuczenski** [comment]
based on post by @loqs, symlinking the compiler directory was probably a band-aid; maybe unrelated but I was unable to `modprobe -r` the resulting module (permanent hang). building in a clean repo was the better fix.

**Comment by benallard** [comment]
@lwfinger Would you accept a pull-request cleaning ``.cache.mk`` as part of the ``make clean`` ?

**Comment by lwfinger** [comment]
Yes, but put it in all branches.
