### ISSUE TITLE
Compilation failed for rtl8723be driver on Xubuntu 16.04.2

### ISSUE THREAD

**Issue by czeni** [lwfinger/rtlwifi_new#215]
After kernel update the module is failed to compile:

```
Unpacking linux-headers-4.8.0-36-generic (4.8.0-36.36~16.04.1) ...
Setting up linux-headers-4.8.0-36 (4.8.0-36.36~16.04.1) ...
Setting up linux-headers-4.8.0-36-generic (4.8.0-36.36~16.04.1) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.8.0-36-generic /boot/vmlinuz-4.8.0-36-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/rtlwifi-new-dkms.0.crash'
Error! Bad return status for module build on kernel: 4.8.0-36-generic (x86_64)
Consult /var/lib/dkms/rtlwifi-new/0.10/build/make.log for more information.
```
 
The log file contains the following:

```
cat /var/lib/dkms/rtlwifi-new/0.10/build/make.log
DKMS make.log for rtlwifi-new-0.10 for kernel 4.8.0-36-generic (x86_64)
2017. márc.  8., szerda, 14:55:54 CET
make: Entering directory '/usr/src/linux-headers-4.8.0-36-generic'
  LD      /var/lib/dkms/rtlwifi-new/0.10/build/built-in.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.10/build/base.o
In file included from /var/lib/dkms/rtlwifi-new/0.10/build/base.c:30:0:
/var/lib/dkms/rtlwifi-new/0.10/build/wifi.h:1327:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:138:10: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_2GHZ,
          ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:150:10: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_5GHZ,
          ^
scripts/Makefile.build:289: recipe for target '/var/lib/dkms/rtlwifi-new/0.10/build/base.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.10/build/base.o] Error 1
Makefile:1491: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.10/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.10/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.8.0-36-generic'
```

My kernel version:
```
uname -a
Linux HP-ProBook 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dracoo** [comment]
Same here with 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lwfinger** [comment]
That API change was handled on December 2, 2016. I just checked the build of the current HEAD against kernels 4.7, 4.8 and 4.9. Everything is OK.

If you have not updated your source recently, that might explain your problem. Otherwise, you are a victim of Ubuntu's nasty habit of changing the API of kernel x by backporting material from kernel x+1. My code is designed to build against vanilla kernel sources. I cannot, and will not, attempt to handle all the situations that arise from any distro's behavior.

You might need to modify wifi.h for your system.

**Comment by belugame** [comment]
Can someone show me how to solve this? I'm on 4.8.0-46-generic as well.

**Comment by lwfinger** [comment]
This kind of question makes me want to delete the entire GitHub repo and force you to be on your own. This time, and only once, I will offer a clue.

In wifi.h, you will see code that looks like the following:

#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 7, 0))
#define nl80211_band ieee80211_band
#define NL80211_BAND_2GHZ IEEE80211_BAND_2GHZ
#define NL80211_BAND_5GHZ IEEE80211_BAND_5GHZ
#define NUM_NL80211_BANDS IEEE80211_NUM_BANDS
#endif

I have no idea what Ubuntu changed, and I have no interest in researching the issue. If they adhered to the policy of NOT changing the API for a given version of the kernel, this would work. My only suggestion is that you either change to a distro that follows the rules, or you change that "7" in the KERNEL_VERSION(4, 7, 0) to see if some other number works.

**Comment by belugame** [comment]
Appreciate your help. You should consider that the average Ubuntu user does not know anything about the implications of editing a system file and may for rational reasons be cautious about it.

**Comment by shahbaz275817** [comment]
Same issue with CentOS 7.
Anyway I solved the driver issue..I didn't have to compile those source files . Just update your kernel headers (since you are on ubuntu apt-get upgrade is recommended) , reboot and just issue these commands as root
modeprobe -rv rtl8723be (or replace 8723be with whatever wireless adapter you have)
modeprobe -v rtl8723be ips=0 ant_sel=1 (or try different combinations untill it works)

It should work now..at it least worked for me

create the file /etc/modeprobe.d/50-rtl8723be.conf
and type there
options rtl8723be ips=0 ant_sel=1

this makes the kernel module change survive reboot (thanks @pezarro)

**Comment by amfrank** [comment]
I can see many people bug the developer with silly questions.. I faced this issue on both Ubuntu and CentOS. What I found is, the driver which ubuntu or CentOS shipped is the latest one. There is no need of downloading and compiling the drivers without testing the installed driver with different antenna selections. In most cases re-enabling the kernel module with correct antenna selection will help.  Let me share my finding.. 

To fix this you have to remove the current kernel modules and then insert it again with the new antenna selection.. In my case, In Ubuntu the antenna was 2 and in centOS7 it is 1. 

So here are the steps (which I did). 

In UBUNTU (16.10, 17.04)
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=2
echo "options rtl8723be ant_sel=2" | sudo tee /etc/modprobe.d/50-rtl8723be.conf 

In CENTOS7
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=1
echo "options rtl8723be ant_sel=1" | sudo tee /etc/modprobe.d/50-rtl8723be.conf

Try this first.  If your first antenna selection is not working then go with the other one. If this step is not helping then try download and compile it.
