### ISSUE TITLE
Unable to Compile in CentOS 8

### ISSUE THREAD

**Issue by drkhosla** [lwfinger/rtlwifi_new#62]
When I try to compile in CentOS I get following error.

[root@localhost rtlwifi_new]# make
make -C /lib/modules/3.10.0-229.7.2.el7.x86_64/build M=/root/rtlwifi_new modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-229.7.2.el7.x86_64'
  CC [M]  /root/rtlwifi_new/base.o
/root/rtlwifi_new/base.c: In function ‘_rtl_init_mac80211’:
/root/rtlwifi_new/base.c:489:21: error: request for member ‘flags’ in something not a structure or union
    hw->wiphy->wowlan.flags = WIPHY_WOWLAN_MAGIC_PKT;
                     ^
/root/rtlwifi_new/base.c:491:21: error: request for member ‘n_patterns’ in something not a structure or union
    hw->wiphy->wowlan.n_patterns =
                     ^
/root/rtlwifi_new/base.c:493:21: error: request for member ‘pattern_min_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_min_len =
                     ^
/root/rtlwifi_new/base.c:495:21: error: request for member ‘pattern_max_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_max_len =
                     ^
make[2]: *** [/root/rtlwifi_new/base.o] Error 1
make[1]: *** [_module_/root/rtlwifi_new] Error 2
make[1]: Leaving directory`/usr/src/kernels/3.10.0-229.7.2.el7.x86_64'
make: **\* [all] Error 2

**Comment by lwfinger** [comment]
The code compiles on a vanilla 3.10 source - this is a CentOS problem. They, like several other distros, modify several API's to match that of later kernels. As a result, my tests for the calls to use for a given kernel version break down. To fix it for you would break most other users, and I refuse to do that, as the API should *NEVER* be backported that way. You will need to fix it yourself.

To do that, try changing the version number in the line that says "#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 11, 0))". I think you need a 10 where I have 11, but that is only a guess. There will likely be other similar changes needed.

**Comment by cj4777** [comment]
I was changed every 3,10,0 to 3,11,0, bug it doesn't work for me, any help please

**Comment by cj4777** [comment]
It's my bad, I decide change centos 7 to fedora, hope it worked

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
