### ISSUE TITLE
Unable to build on 3.10.0-229.1.2.el7.x86_64

### ISSUE THREAD

**Issue by jvell** [lwfinger/rtlwifi_new#40]
If more info is needed just let me know.

```
make -C /lib/modules/3.10.0-229.1.2.el7.x86_64/build M=/root/rtlwifi_new modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-229.1.2.el7.x86_64'
  CC [M]  /root/rtlwifi_new/pci.o
  CC [M]  /root/rtlwifi_new/usb.o
  CC [M]  /root/rtlwifi_new/base.o
/root/rtlwifi_new/base.c: In function ‘_rtl_init_mac80211’:
/root/rtlwifi_new/base.c:476:21: error: request for member ‘flags’ in something not a structure or union
    hw->wiphy->wowlan.flags = WIPHY_WOWLAN_MAGIC_PKT;
                     ^
/root/rtlwifi_new/base.c:478:21: error: request for member ‘n_patterns’ in something not a structure or union
    hw->wiphy->wowlan.n_patterns =
                     ^
/root/rtlwifi_new/base.c:480:21: error: request for member ‘pattern_min_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_min_len =
                     ^
/root/rtlwifi_new/base.c:482:21: error: request for member ‘pattern_max_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_max_len =
                     ^
make[2]: *** [/root/rtlwifi_new/base.o] Error 1
make[1]: *** [_module_/root/rtlwifi_new] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-229.1.2.el7.x86_64'
```

**Comment by lwfinger** [comment]
Is that an Ubuntu kernel? If so, I cannot support it.

The reason is that the idiots at Ubuntu are backporting API changes to older kernel versions. That makes it impossible to detect the features of a given kernel using the LINUX_VERSION_CODE and KERNEL_VERSION macros. When I first discovered this faulty behavior by Ubuntu, I wasted a lot of time trying to discover why the driver would not build. My time is valuable even though I am not getting paid! I will not waste it this way.

**Comment by jvell** [comment]
It's a CentOS/RedHat kernel.

Your tree works flawless against the previous version of their kernel source, 3.10.0-123.20.1.el7.x86_64. At least when I build it around February 26th.

I've tried to build an older revision (February 26th) of the tree against the new kernel but the error is the same. So I'm pretty sure it's their changes that broke the build. My git and c fu is quite low so I could have screwed up building the older revision.

The error is reproducible against HEAD of today.

If I can safe your time by providing more information, just ask.

**Comment by lwfinger** [comment]
I have confirmed that Centos/RedHat are doing the same kind of screwing up the kernel headers as has been done by Ubuntu!

Fixing the drivers to build on your system would break it on every other system. That hardly seems fair. The best I can do is show you how to fix it for yourself. In base.c at line 472, you will find a line that says

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 11, 0))

Change that 11 to a 10, and it should build, at least for this part.

**Comment by jvell** [comment]
Thank you for confirming the problem is in the Centos/RedHat kernel headers. 

As you probably expected more changes are needed to get a full build. The one change even breaks the build on the previous kernel headers.

Are you interested in the full change set, if I get it all building/working?

**Comment by lwfinger** [comment]
Yes. I could not apply it, but having such a patch set might be useful for some other Centos user.

**Comment by jvell** [comment]
I've been able to mutilate your tree in such a way that I was able to get it to build without erros. :-)

Major panic loading the module :-S

RedHat did a proper job breaking compatibility.

Next stop the bugtracker for CentOS.

**Comment by jvell** [comment]
Bug report submitted:
http://bugs.centos.org/view.php?id=8385

I will use copper or the older kernel to have network.

Thanks for your help so far!

**Comment by jvell** [comment]
As advised in: http://bugs.centos.org/view.php?id=8385#c22658
Bug reported to Red Hat:
https://bugzilla.redhat.com/show_bug.cgi?id=1208980

Fingers crossed.

**Comment by jvell** [comment]
The ElRepo guys managed to make it work against my kernel.
http://elrepo.org/bugs/view.php?id=567

Waiting for more information on how they did it.

**Comment by jvell** [comment]
RH just closed my bugreport, itsnotabug...

https://bugzilla.redhat.com/show_bug.cgi?id=1208980

> Stanislaw Gruszka 2015-04-06 03:34:56 EDT:
> Execpt what is listed in kABI, we do not promise to do not change symbols on RHEL7 kernel. This build problem should be fixed on rtlwifi driver.

So I guess I need to find a distro that does promise not to change symbols on their kernel?

**Comment by lwfinger** [comment]
I have been an openSUSE user for over 15 years. They do not change the kernel API. My preference is the KDE desktop, but they also offer Gnome and a host of other flavors of desktop.

**Comment by RainbowDashDC** [comment]
Arch Linux doesn't change theirs either, just to throw that out there. But the drawback (or plus) is that it's a Rolling Release.

**Comment by wmzy** [comment]
@lwfinger 
"Fixing the drivers to build on your system would break it on every other system. That hardly seems fair. The best I can do is show you how to fix it for yourself. In base.c at line 472, you will find a line that says

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 11, 0))

Change that 11 to a 10, and it should build, at least for this part."

also unable to build.
need help!
thanks!

**Comment by lwfinger** [comment]
Yes, that part builds, but then you need to override CONFIG_PM, and that would break supension and hibernation. When I reached that point, I gave up. Unless someone pays me for the consulting time, I will not try to shoehorn this code into a kernel in which the APIs have been mutilated.

As jvell is doing, I recommend that you find a distro that does not engage in this kind of behavior, or you build a 3.9.3 kernel - that has all the latest changes and you will not need this repo.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
