### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by thewh1teagle** [lwfinger/rtlwifi_new#580]
debian 10 x64

```
sudo apt-get install linux-headers-`uname -r` build-essential git
git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make
```

```


/tmp/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/tmp/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
```

**Comment by thewh1teagle** [comment]
i tried to comment out the line of initialize the variable in the struct ( .alloc = rtl_rate_alloc, )
the build worked.
but after that the driver not worked ( actually the os is not booted )

**Comment by lwfinger** [comment]
You remove a critical part of the callback system from mac80211 to the driver, and then you seem surprised that it does not work!!!!!!

**Comment by thewh1teagle** [comment]
It's debian buster. fresh install. 
I didn't removed anything.

**Comment by lwfinger** [comment]
With Debian, you sometimes need to run the following:

sudo ln -s  /lib/modules/$(uname -r)/build /usr/src/$(uname -r)/x86_64/default

**Comment by yoann-dev** [comment]
Hello @thewh1teagle,

I have encountered the same problem ( #578 ),  so I have forked this repository to work on master/extended branch for Debian 10 : https://github.com/yoann-dev/rtlwifi_new/

**Comment by thewh1teagle** [comment]
@yoann-dev 
You awesome!
@lwfinger  why not merge his fixing.. i think it will help for other people. 
anyway, thank you all.

**Comment by Gissp** [comment]
buenas tardes disculpen si me pueden guiar hallar una solucion despues de realizar la  respectiva instalacion para este controlador rtl8723de tengo un sistema  kali linux virtulizado con vmware  y windows 10 por default  en una  HP :( losé 
`root@root:/home/kalinux/rtlwifi_new# uname --all
Linux root 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
`
este es mi error :

`Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
make -j2 KERNELRELEASE=5.5.0-kali2-amd64 -C /lib/modules/5.5.0-kali2-amd64/build M=/var/lib/dkms/rtlwifi-new/0.6/build.................................................................................................(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.5.0-kali2-amd64 (x86_64)
Consult /var/lib/dkms/rtlwifi-new/0.6/build/make.log for more information.
root@root:/home/kalinux/rtlwifi_new# sudo modprobe -v rtl8723de ant_sel=2
modprobe: FATAL: Module rtl8723de not found in directory **/lib/modules/5.5.0-kali2-amd64
`**
gracias por su atencion y tiempo

**Comment by thewh1teagle** [comment]
Hola
Necesito que pegues el registro aquí
/var/lib/dkms/rtlwifi-new/0.6/build/make.log

**Comment by thewh1teagle** [comment]
> 
> 
> buenas tardes disculpen si me pueden guiar hallar una solucion despues de realizar la respectiva instalacion para este controlador rtl8723de tengo un sistema kali linux virtulizado con vmware y windows 10 por default en una HP :( losé
> `root@root:/home/kalinux/rtlwifi_new# uname --all Linux root 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux `
> este es mi error :
> 
> `Kernel preparation unnecessary for this kernel. Skipping...
> 
> Building module:
> cleaning build area...(bad exit status: 2)
> make -j2 KERNELRELEASE=5.5.0-kali2-amd64 -C /lib/modules/5.5.0-kali2-amd64/build M=/var/lib/dkms/rtlwifi-new/0.6/build.................................................................................................(bad exit status: 2)
> Error! Bad return status for module build on kernel: 5.5.0-kali2-amd64 (x86_64)
> Consult /var/lib/dkms/rtlwifi-new/0.6/build/make.log for more information.
> root@root:/home/kalinux/rtlwifi_new# sudo modprobe -v rtl8723de ant_sel=2
> modprobe: FATAL: Module rtl8723de not found in directory **/lib/modules/5.5.0-kali2-amd64 `**
> gracias por su atencion y tiempo



Hola
Necesito que pegues el registro aquí
/var/lib/dkms/rtlwifi-new/0.6/build/make.log

**Comment by lwfinger** [comment]
dkms is failing to build as shown by "/build.................................................................................................(bad exit status: 2)"

I have no idea why.

**Comment by Gissp** [comment]
muchas gracias por tu respuesta
aqui esta make log-----
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: error: initialization of
‘void * (*)(struct ieee>
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: note: (near initialization
for ‘rtl_rate_ops.all>
cc1: some warnings being treated as errors
make[2]: ***
[/usr/src/linux-headers-5.5.0-kali2-common/scripts/Makefile.build:271:
/var/lib/dkms>
make[2]: *** Se espera a que terminen otras tareas....
make[1]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:1707:
/var/lib/dkms/rtlwifi-new/>
make: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:179:
sub-make] Error 2
make: se sale del directorio '/usr/src/linux-headers-5.5.0-kali2-amd64'
Error! Bad return status for module build on kernel: 5.5.0-kali2-amd64
(x86_64)
modprobe: FATAL: Module rtl8723de not found.
modprobe: FATAL: Module rtl8723de not found in directory
/lib/modules/5.5.0-kali2-amd64

**Comment by Gissp** [comment]
cuando realizo sudo dkms install rtlwifi-new/0.6
  GNU nano 4.9.2                               make.log

  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_math_lib.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_api.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_pow_train.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/rtl8192ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halphyrf_ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/hw.o
  CC [M]
 /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_powertracking_ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/led.o
  CC [M]
 /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_powertracking.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/mac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_kfree.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/phy.o
  CC [M]
 /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/rtl8822b/halrf_8822b.o

^G Ver ayuda    ^O Guardar      ^W Buscar       ^K Cortar       ^J
Justificar   ^C Posición
^X Salir        ^R Leer fich.   ^\ Reemplazar   ^U Pegar        ^T
Ortografía   ^_ Ir a línea

**Comment by thewh1teagle** [comment]
same error as mine, wich os? debian ?

**Comment by lwfinger** [comment]
For the Makefile to determine how many arguments are needed for the .alloc member of struct rate_control_ops, it needs to reach file include/net/mac80211.h. My system defines a link from /lib/modules/$(uname -r)/build to /usr/src/$(uname -r)/default. Your system should also create such a link to where ever .../include/net/mac80211.h resides.

**Comment by Gissp** [comment]
efectivamente utilizo una distribucion de debian kali

**Comment by Gissp** [comment]
la verdad nose como establecer ese vinculo  pero no dejare de intentarlo

**Comment by Gissp** [comment]
encontre el archivo mac80211.h

**Comment by Gissp** [comment]
disculpa edite en Makefile y cambie el directorio de Determine # args for
rtl_rate_alloc
TEMP=$(shell grep alloc ${KSRC}/include/net/mac80211.h | grep void | grep
dentry)     a
Determine # args for rtl_rate_alloc
TEMP=$(shell grep alloc ${KSRC}nclude/config /mac80211.h | grep void | grep
dentry)
 pero al seguir con el make me vuele a salir esto

**Comment by lwfinger** [comment]
The new driver for RTL8723DE is now in the wireless_drivers_next repo. To make it easier for users here, it is now in the rtw88 branch. Do the following:

git checkout origin/rtw88 -b rtw88
make
sudo make install

This version should build on kernels 4.5 or newer.

Please be aware that on June 1, 2020, all branches in this repo will be deleted except for rtw88. If you really need the other drivers for old kernels, use the "backports" project. These old drivers have been taking too much of my time!

**Comment by yoann-dev** [comment]
Thank you very much @lwfinger for your work !

I tried to compile on the rtw88 branch with the 4.19 kernel, it doesn't work. Could you give me the repository url for the backports project ?

Thanks

**Comment by lwfinger** [comment]
https://backports.wiki.kernel.org/index.php/Main_Page

For kernels as new as 4.19, branch rtw88 should build. Please post your errors. Also be aware that the driver for RTL8723DE is not in backports yet.

**Comment by yoann-dev** [comment]
Hello @lwfinger 

Thanks for your answer. My build problem with RTL8723DE and 4.19 kernel seems to look similar to the #583 issue. 

For the moment, I will follow the #583 issue to avoid duplicate bug report.

**Comment by thewh1teagle** [comment]
@yoann-dev 
Hi
i tried to install your fork of this repository 
i compiled successsfuly but when i try to load the module i get error which the module is not signed 

```
modprobe -r rtl8192de
modprobe rtl8192de
```

```
dmesg -w
module verification failed: signature and/or required key missing - tainting kernel
``` 

debian 10 x86_64

kernel version 4.19.0-9-amd64

**Comment by lwfinger** [comment]
If you have secure boot enabled, then you cannot load such modules. I do not sign them.

If secure boot is disabled, then this is just an informative message.

**Comment by thewh1teagle** [comment]
@lwfinger 
secure boot is disabled in bios
wdym infomative message?

**Comment by lwfinger** [comment]
I do not know. You would need to ask Debian to find out how to load unsigned modules, or how to sign them. It works for me.

**Comment by thewh1teagle** [comment]
@lwfinger 
actually i know how to insert it. i installed specific kernel that allow me to insert unsigned module.
and after that i recompiled and installed the module.
and now i get this error when modprobing
```
modprobe -r rtl8192de && sudo modprobe rtl8192de

dmesg -w
loading out-of-tree module taints kernel.
```

**Comment by lwfinger** [comment]
rtl8192de is in the extended branch, which I am no longer supporting in any way. I will not delete it until June 1.
The driver for the RTL8723DE that is supported is rtw_8723de. The in-kernel driver is rtw88_8723de.

**Comment by thewh1teagle** [comment]
i am talking about rtl8192de 
not rtl8723de

**Comment by lwfinger** [comment]
You need to hang on to your source, find another repo. get a newer kernel, or use the backports project. I know it will be inconvenient; however, getting 20 E-mails every day with just plain stupid errors, and a total lack of information pushed me over the edge. I will be 80 years old tomorrow, and I have lost all patience.

**Comment by thewh1teagle** [comment]
I understand.
I upgraded my debian to testing and then i installed newer kernel (5+)
and now the driver is builtin the kernel. 
thanks for all of your help.
