### ISSUE TITLE
Unable to build on 3.10.0-229.1.2.el7.x86_64 bug not resolved

### ISSUE THREAD

**Issue by wnemail** [lwfinger/rtlwifi_new#46]
make -C /lib/modules/3.10.0-229.1.2.el7.x86_64/build M=/root/rtlwifi_new modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-229.1.2.el7.x86_64'
  CC [M]  /root/rtlwifi_new/pci.o
  CC [M]  /root/rtlwifi_new/usb.o
  CC [M]  /root/rtlwifi_new/base.o
/root/rtlwifi_new/base.c: In function ‘_rtl_init_mac80211’:
/root/rtlwifi_new/base.c:476:21: error: request for member ‘flags’ in something not a structure or union
    hw->wiphy->wowlan.flags = WIPHY_WOWLAN_MAGIC_PKT;
                     ^
/root/rtlwifi_new/base.c:478:21: error: request for member ‘n_patterns’ in something not a structure or union
    hw->wiphy->wowlan.n_patterns =
                     ^
/root/rtlwifi_new/base.c:480:21: error: request for member ‘pattern_min_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_min_len =
                     ^
/root/rtlwifi_new/base.c:482:21: error: request for member ‘pattern_max_len’ in something not a structure or union
    hw->wiphy->wowlan.pattern_max_len =
                     ^
make[2]: *** [/root/rtlwifi_new/base.o] Error 1
make[1]: *** [_module_/root/rtlwifi_new] Error 2
make[1]: Leaving directory`/usr/src/kernels/3.10.0-229.1.2.el7.x86_64'

**Comment by lwfinger** [comment]
The source compiles perfectly fine on my *vanilla* 3.10.0 source. One rule of kernel development concerns the API, which includes the argument list of routines, the variables in the various structures, and similar quantities. The API is allowed to change between major versions of the kernel, but not normally with minor versions. Your problem is that your distro has idiotically backported kernel API changes across kernel versions. Once they do that, it is no longer enough to use the KERNEL_VERSION macro to detect the API and correctly compile out-of-kernel drivers.

When I first encountered this problem, I wasted several hours trying to determine what was wrong. Once I discovered the source of the problem, I decided not to do that again. If I tried to follow all of this type of change, it would consume all my time.

You should switch to a newer version of your distro, a newer kernel for your current distro release, or switch to a distro that does not practice this idiotic behavior.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
