### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.10.0-35-generic (x86_64)

### ISSUE THREAD

**Issue by inkss** [lwfinger/rtlwifi_new#276]
```
DKMS make.log for rtlwifi-new-0.10 for kernel 4.10.0-35-generic (x86_64)

make: Entering directory '/usr/src/linux-headers-4.10.0-35-generic'
  LD      /var/lib/dkms/rtlwifi-new/0.10/build/built-in.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.10/build/base.o
In file included from /var/lib/dkms/rtlwifi-new/0.10/build/base.c:30:0:
/var/lib/dkms/rtlwifi-new/0.10/build/wifi.h:1327:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:138:10: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_2GHZ,
          ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:150:10: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_5GHZ,
          ^
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/rtlwifi-new/0.10/build/base.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.10/build/base.o] Error 1
Makefile:1524: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.10/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.10/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.10.0-35-generic'
```

**Comment by inkss** [comment]
```
DKMS make.log for rtlwifi-new-0.10 for kernel 4.10.0-35-generic (x86_64)
2017年 10月 08日 星期日 02:04:47 CST
make: Entering directory '/usr/src/linux-headers-4.10.0-35-generic'
  LD      /var/lib/dkms/rtlwifi-new/0.10/build/built-in.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.10/build/base.o
In file included from /var/lib/dkms/rtlwifi-new/0.10/build/base.c:30:0:
/var/lib/dkms/rtlwifi-new/0.10/build/wifi.h:1327:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:138:10: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_2GHZ,
          ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:150:10: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_5GHZ,
          ^
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/rtlwifi-new/0.10/build/base.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.10/build/base.o] Error 1
Makefile:1524: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.10/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.10/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.10.0-35-generic'
```

**Comment by lwfinger** [comment]
Are you aware that this is a multi-branch repository? Because it is, you need to specify which branch you are using!

In this case, however, that missing information is not critical. On my system, using kernels from kernel.vger.org, all branches build correctly. I suspect that you are using Ubuntu kernels, and that they have once again violated the prohibition against kernel API changes in the middle of a major kernel version. This change breaks the method of testing kernel versions for code changes.

I decided a long time ago that I would never reward this bad behavior by fixing the code as that would break it for all other users. As a result, you are on your own. There is a section in the code that handles this case. By doing a search for the missing symbols, you will find the critical section.

**Comment by inkss** [comment]
it's Ubuntu16.04 operating system.
Its kernel is 4.10.? (Not remember).
Just how can I solve this problem now?
(With google translation, uh, english is not too good)

**Comment by eisterman** [comment]
Need more information about your system.
What kernel you have? 
Is a custom kernel?
Did you installed the Linux-Header of the same version of your kernel? And if is a custom kernel you have the right header for it?

**Comment by lekseven** [comment]
I'm also having the same issue. I'm on an official Ubuntu kernel. All headers are installed.

**uname -a**
```
Linux lunatic-pc 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**lsb_release -a**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**sudo apt-get install rtlwifi-new-dkms**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rtlwifi-new-dkms
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 658 kB of archives.
After this operation, 6 809 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/hanipouspilot/rtlwifi/ubuntu xenial/main amd64 rtlwifi-new-dkms all 0.10 [658 kB]
Fetched 658 kB in 4s (133 kB/s)            
Selecting previously unselected package rtlwifi-new-dkms.
(Reading database ... 712805 files and directories currently installed.)
Preparing to unpack .../rtlwifi-new-dkms_0.10_all.deb ...
Unpacking rtlwifi-new-dkms (0.10) ...
Setting up rtlwifi-new-dkms (0.10) ...
Loading new rtlwifi-new-0.10 DKMS files...
First Installation: checking all kernels...
Building only for 4.10.0-38-generic
Building for architecture x86_64
Building initial module for 4.10.0-38-generic
Error! Bad return status for module build on kernel: 4.10.0-38-generic (x86_64)
Consult /var/lib/dkms/rtlwifi-new/0.10/build/make.log for more information.
```

**/var/lib/dkms/rtlwifi-new/0.10/build/make.log**
```
DKMS make.log for rtlwifi-new-0.10 for kernel 4.10.0-38-generic (x86_64)
Вс ноя 12 02:58:56 +07 2017
make: Entering directory '/usr/src/linux-headers-4.10.0-38-generic'
  LD      /var/lib/dkms/rtlwifi-new/0.10/build/built-in.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.10/build/base.o
In file included from /var/lib/dkms/rtlwifi-new/0.10/build/base.c:30:0:
/var/lib/dkms/rtlwifi-new/0.10/build/wifi.h:1327:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:138:10: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_2GHZ,
          ^
/var/lib/dkms/rtlwifi-new/0.10/build/base.c:150:10: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_5GHZ,
          ^
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/rtlwifi-new/0.10/build/base.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.10/build/base.o] Error 1
Makefile:1524: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.10/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.10/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.10.0-38-generic'
```

**Comment by lwfinger** [comment]
The official Ubuntu kernel is the problem. On all mainline kernels, no one is allowed to change a kernel API except at major kernel boundaries. That way external modules can test the kernel version to determine which API to use. Ubuntu, on the other hand, backports API changes to older kernels. As a result, your kernel 4.10.0 has changes that were not applied to mainline kernels 4.11.0, 4.12.0, etc., and my carefully written test fails!

I am very much against this practice, and I refuse to modify my kernel source to support the practice. As long as you continue to use Ubuntu kernels, you will need to make the modifications yourself!!
