### ISSUE TITLE
Kernel 4.4.21+ Compile Problem

### ISSUE THREAD

**Issue by parithy** [lwfinger/rtlwifi_new#123]
Hi 
There seems to be some problem in compiling the master branch against Kernels above 4.4.21
There are lot of post with similar errors, but none helped. Not sure if this is problem with the build tool chain or kernel or the driver code. I have tried installing rc kernels like 4.6RC6 but the error continuous to be there. So it is not going to get fix by upgrading the kernel anytime soon. I have also tried reinstalling build-essentials, gcc, make packages in ubuntu. Nothing  fixed the problem. Could you let me know your opinion?

$ sudo make
make -C /lib/modules/4.4.0-22-generic/build M=/home/***************_/wififix/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-22-generic'
arch/x86/Makefile:133: stack-protector enabled but compiler support broken
Makefile:670: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  CC [M]  /home/**_*************_/wififix/rtlwifi_new/base.o
/home/**_****************_/wififix/rtlwifi_new/base.c:1:0: error: code model kernel does not support PIC mode
 /**_***************************************************************************
 ^
scripts/Makefile.build:258: recipe for target '/home/**************_**/wififix/rtlwifi_new/base.o' failed
make[2]: *_\* [/home/*********************_/wififix/rtlwifi_new/base.o] Error 1
Makefile:1396: recipe for target '_module_/home/**_*********_**/wififix/rtlwifi_new' failed
make[1]: *_\* [_module_/home/*********************_**/wififix/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-22-generic'
Makefile:57: recipe for target 'all' failed
make: *_\* [all] Error 2
$ git fetch
$ git pull
Already up-to-date.
$ gcc --version
gcc (Ubuntu 5.3.1-19ubuntu1) 5.3.1 20160509
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by lwfinger** [comment]
It appears that Ubuntu is using a different compiler for the kernel than the one you have installed. The command "dmesg | grep Linux\ version" will show what version was used by them to build the kernel.

From a number of similar complaints, it seems that Ubuntu is making it hard to build out-of-kernel modules. Whether it is deliberate is an open question.

**Comment by parithy** [comment]
I see the version to be the same but the gcc build date to be different

$ dmesg | grep Linux\ version
[    0.000000] Linux version 4.4.0-22-generic (buildd@lgw01-41) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 (Ubuntu 4.4.0-22.40-generic 4.4.8)


1) Is there any work around for this error in terms of setting flags in the make command/file?
2)Could you tell me how I can get the detail of what commit of repository is in the Kernel mainline driver?

Thanks for the prompt reply

**Comment by lwfinger** [comment]
The gcc versions are not quite the same. The kernel was built with 5.3.1-14ubuntu2 and you have 5.3.1-19ubuntu1.

1) There are no flags that can be set. Once the kernel is built with CONFIG_CC_STACKPROTECTOR_STRONG=y, then all modules must be built to conform. I'm surprised that Ubuntu distributes a kernel with that config variable set. That test is good when you are debugging, but it does slow down the resulting kernel, thus it is not generally set for distributed kernels.

2) The drivers in this repo are roughly the equivalent of the drivers in the wireless-drivers-next repo, or those in the net-next repo. Those drivers are then ones that will be in kernel 4.7. All fixes in those repos are ported here, and vice versa. Due to the more rigorous review process, patches sent to the -next repos are available sometime after they are included here. There is, however, no direct correlation between a given kernel version and the code here. The Ubuntu kernel here is 4.4.8 with local modifications. I have no idea what the differences are between that and the current 4.6.0 due to the Ubuntu mods.

One work aroud would be to download the source from Ubuntu or mainline and build a custom kernel. Kernel builds are not that difficult.

**Comment by parithy** [comment]
Unfortunately, I am getting the same error even when I try to build the kernel source. So it probably has nothing to do with your code or makefile. I have been using kernels from dev channel. The reason you mentioned "That test is good when you are debugging, but it does slow down the resulting kernel, thus it is not generally set for distributed kernels." may apply because the kernel in my computer is not a production build.


Also, you mentioned "all modules must be built to conform". How do I build your code to conform to the CONFIG_CC_STACKPROTECTOR_STRONG=y requirement? I have secure boot enabled just FYI. It has been on for a very long time. Never had a problem because of it. I am wondering if the problem is some sort of combination of multiple causes.

There is also one more error "code model kernel does not support PIC mode"

**Comment by parithy** [comment]
Ubuntu kernel 4.4.0-23 which came from the dev apt-get repository no longer has the issue.

**Comment by k3dves** [comment]
Hi, 
I am having the same problem , after i updated my kali linux kernel to 4.8.0-kali1-amd64.
When I type 'make install' it shows the following error::



root@localhost:~/Downloads/rtlwifi_new-master# make install
make -C /lib/modules/4.8.0-kali1-amd64/build M=/root/Downloads/rtlwifi_new-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-kali1-amd64'
  CC [M]  /root/Downloads/rtlwifi_new-master/base.o
/root/Downloads/rtlwifi_new-master/base.c:1:0: error: code model kernel does not support PIC mode
 /******************************************************************************
 
/usr/src/linux-headers-4.8.0-kali1-common/scripts/Makefile.build:294: recipe for target '/root/Downloads/rtlwifi_new-master/base.o' failed
make[4]: *** [/root/Downloads/rtlwifi_new-master/base.o] Error 1
/usr/src/linux-headers-4.8.0-kali1-common/Makefile:1488: recipe for target '_module_/root/Downloads/rtlwifi_new-master' failed
make[3]: *** [_module_/root/Downloads/rtlwifi_new-master] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-kali1-amd64'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
root@localhost:~/Downloads/rtlwifi_new-master# 

It would be very kind , if you could help me in getting around this issue.

**Comment by lwfinger** [comment]
That PIC mode request is NOT in my code. You will need to resolve this with KALI. I do not run that distro, and I have no idea what part is their system is at fault. No, I will not install KALI to see what is wrong!

**Comment by k3dves** [comment]
Thanks for the quick reply @lwfinger 
Looks like I have to downgrade my kernel .

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
