### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by gobi25** [lwfinger/rtlwifi_new#330]
I tried to install this driver in Debian 9.

When run below command I get following Error 

`dkms install rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414`

**ERROR**

```
/bin/sh: 1: bc: not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-6-amd64/build M=/home/gobinath/Downloads/rtl8723de  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-6-amd64'
/bin/sh: 1: bc: not found
  CC [M]  /home/gobinath/Downloads/rtl8723de/core/rtw_cmd.o
In file included from /home/gobinath/Downloads/rtl8723de/include/drv_types.h:32:0,
                 from /home/gobinath/Downloads/rtl8723de/core/rtw_cmd.c:22:
/home/gobinath/Downloads/rtl8723de/include/osdep_service.h:41:33: fatal error: linux/sched/signal.h: No such file or directory
  #include <linux/sched/signal.h>
                                 ^
compilation terminated.
/usr/src/linux-headers-4.9.0-6-common/scripts/Makefile.build:298: recipe for target '/home/gobinath/Downloads/rtl8723de/core/rtw_cmd.o' failed
make[4]: *** [/home/gobinath/Downloads/rtl8723de/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.9.0-6-common/Makefile:1515: recipe for target '_module_/home/gobinath/Downloads/rtl8723de' failed
make[3]: *** [_module_/home/gobinath/Downloads/rtl8723de] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-6-amd64'
Makefile:1884: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by lwfinger** [comment]
First of all, you need to install "bc" using "sudo apt-get install bc" or some such package manager command.

As to the problem with signal.h, i cannot tell what source you are using. As far as I know, my sources should build on kernels from 4.16 to 4.1, unless the distro has backported API changes. I do not support that case.
