### ISSUE TITLE
Compilation error in function ‘ewma_snr_read’ 

### ISSUE THREAD

**Issue by Nerhbest** [lwfinger/rtlwifi_new#605]
Error was occured during make
My OS: Ubuntu 16.04  
Kernel: 4.8.0-36-generic

*********************************************************************************************************************

make -C /lib/modules/4.8.0-36-generic/build M=/home/nerh/Downloads/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-36-generic'
  CC [M]  /home/nerh/Downloads/rtlwifi_new/debug.o

In file included from ./include/linux/linkage.h:4:0,
                 from ./include/linux/fs.h:4,
                 from ./include/linux/debugfs.h:18,
                 from /home/nerh/Downloads/rtlwifi_new/debug.c:5:

***************************************************************************************************************************
In function ‘ewma_snr_read’,
    inlined from ‘rtw_debugfs_get_phy_info’ at /home/nerh/Downloads/rtlwifi_new/debug.c:668:11:
./include/linux/compiler.h:491:38: error: call to ‘__compiletime_assert_1493’ declared with attribute error: BUILD_BUG_ON failed: (4) == 0 || (((4) & ((4) - 1)) != 0)
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)

**********************************************************************************************************************
scripts/Makefile.build:289: recipe for target '/home/nerh/Downloads/rtlwifi_new/debug.o' failed
make[2]: *** [/home/nerh/Downloads/rtlwifi_new/debug.o] Error 1
Makefile:1491: recipe for target '_module_/home/nerh/Downloads/rtlwifi_new' failed
make[1]: *** [_module_/home/nerh/Downloads/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-36-generic'
Makefile:79: recipe for target 'all' failed
make: *** [all] Error 2

*****************************************************************************************************
Please tell me about that error and solution to resolve that. Thanks

**Comment by Nerhbest** [comment]
I am looking more closely into README and find notification about kernel version. Closed.

**Comment by lwfinger** [comment]
I am willing to try to get the drivers to work with older kernels; however, 4.8 may not be possible. Is it possible to upgrade to 4.15 or newer?
